name: Check for release-candidate
on:
  pull_request:
    branches: [ develop ]
jobs:
  deployCandidate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Reset deploy branch
        run: |
          git fetch origin develop:main
          git reset --hard develop
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: main-candidate
